version: '3.7'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - "./config/:/config/"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    restart: unless-stopped
    expose:
      - 8123
    networks:
      - web
    #    dns: 192.168.1.6
    #    dns_search: mhd.mccullonas.co.uk
    environment:
      - TZ="UTC"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.hass.rule=Host(`hass.mccullonas.co.uk`)"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"
      - "traefik.http.routers.hass.entrypoints=websecure"
      - "traefik.http.routers.hass.tls.certresolver=le_dns"

networks:
  web:
    external: true

# volumes:
#   config:
