# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.6
    - 127.0.0.1
    - ::1

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#base_url: hass.mccullonas.co.uk

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

#pi_hole:
#  host: 'pihole.mccullonas.co.uk'
#  ssl: true
#  verify_ssl: true
#  api_key: a7a65d945681f0ed84b2073b1de2deb0f712a35c46687fe7ac0084f966fb2502

#evohome:
#  username: admin@andymcculloch.co.uk
#  password: 0uUc@2R^Y*IjWL&o
  #  password: 5rRI08rmJanQk$M&

  #climate:
  #  - platform: honeywell
  #    region: eu
  #    username: andy@andymcculloch.co.uk
  #    password: 5rRI08rmJanQk$M&

sonos:
  media_player:
    advertise_addr: 192.168.1.6
    hosts:
      - BedroomSonos.mhd.mccullonas.co.uk
      - OfficeSonos.mhd.mccullonas.co.uk
      - KitchenSonos.mhd.mccullonas.co.uk
      - DiningRoomSonos.mhd.mccullonas.co.uk
      - GuestRoomSonos.mhd.mccullonas.co.uk
      - LoungeSonos.mhd.mccullonas.co.uk

weather:
  - platform: darksky
    api_key: 96d217ce827e78d1aa78a2b4dc9cfa53
    mode: daily

    #camera:
    #  - platform: onvif
    #    name: Back Garden
    #    host: camera1.mhd.mccullonas.co.uk
    #    username: homeassistant
    #    password: N3nq^318p2YCSt$
    #    port: 80
    #    profile: 1

switch:
  - platform: mqtt
    name: WiFiSwitch4
    state_topic: WiFiSwitch4/relay/0
    command_topic: WiFiSwitch4/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: WiFiSwitch4/status
    payload_available: 1
    payload_not_available: 0
 
  - platform: mqtt
    name: WiFiSwitch3
    state_topic: WiFiSwitch3/relay/0
    command_topic: WiFiSwitch3/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: WiFiSwitch3/status
    payload_available: 1
    payload_not_available: 0
 
  - platform: mqtt
    name: WiFiSwitch2
    state_topic: WiFiSwitch2/relay/0
    command_topic: WiFiSwitch2/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: WiFiSwitch2/status
    payload_available: 1
    payload_not_available: 0
 
logger:
## turn off debug messages, generally...
  default: warn

  logs:
    homeassistant.components.evohome: debug
#   homeassistant.components.climate.evohome: debug
#   homeassistant.components.water_heater.evohome: debug
    evohomeclient2: debug
    evohomeasync: debug
    evohomeasync2: debug


