
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.6
    - 127.0.0.1
    - ::1

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#base_url: hass.mccullonas.co.uk

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#pi_hole:
#  host: 'pihole.mccullonas.co.uk'
#  ssl: true
#  verify_ssl: true
#  api_key: a7a65d945681f0ed84b2073b1de2deb0f712a35c46687fe7ac0084f966fb2502

#evohome:
#  username: admin@andymcculloch.co.uk
#  password: 0uUc@2R^Y*IjWL&o
  #  password: 5rRI08rmJanQk$M&

  #climate:
  #  - platform: honeywell
  #    region: eu
  #    username: andy@andymcculloch.co.uk
  #    password: 5rRI08rmJanQk$M&

sonos:
  media_player:
    hosts:
      - BedroomSonos.mhd.mccullonas.co.uk
      - OfficeSonos.mhd.mccullonas.co.uk
      - KitchenSonos.mhd.mccullonas.co.uk
      - DiningRoomSonos.mhd.mccullonas.co.uk
      - GuestRoomSonos.mhd.mccullonas.co.uk
      - LoungeSonos.mhd.mccullonas.co.uk

weather:
  - platform: darksky
    api_key: 96d217ce827e78d1aa78a2b4dc9cfa53
    mode: daily

    #camera:
    #  - platform: onvif
    #    name: Back Garden
    #    host: camera1.mhd.mccullonas.co.uk
    #    username: homeassistant
    #    password: N3nq^318p2YCSt$
    #    port: 80
    #    profile: 1

switch:
  - platform: mqtt
    name: WiFiSwitch4
    state_topic: WiFiSwitch4/relay/0
    command_topic: WiFiSwitch4/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: WiFiSwitch4/status
    payload_available: 1
    payload_not_available: 0
 
  - platform: mqtt
    name: WiFiSwitch3
    state_topic: WiFiSwitch3/relay/0
    command_topic: WiFiSwitch3/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: WiFiSwitch3/status
    payload_available: 1
    payload_not_available: 0
 
  - platform: mqtt
    name: WiFiSwitch2
    state_topic: WiFiSwitch2/relay/0
    command_topic: WiFiSwitch2/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: WiFiSwitch2/status
    payload_available: 1
    payload_not_available: 0
 
sensor:
  - platform: mqtt
    name: WiFiSwitch2_current
    state_topic: WiFiSwitch2/current
    unit_of_measurement: A
 
  - platform: mqtt
    name: WiFiSwitch2_voltage
    state_topic: WiFiSwitch2/voltage
    unit_of_measurement: V
 
  - platform: mqtt
    name: WiFiSwitch2_power
    state_topic: WiFiSwitch2/power
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch2_reactive
    state_topic: WiFiSwitch2/reactive
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch2_apparent
    state_topic: WiFiSwitch2/apparent
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch2_factor
    state_topic: WiFiSwitch2/factor
    unit_of_measurement: '%'
 
  - platform: mqtt
    name: WiFiSwitch2_energy
    state_topic: WiFiSwitch2/energy
    unit_of_measurement: J
 
  - platform: mqtt
    name: WiFiSwitch3_current
    state_topic: WiFiSwitch3/current
    unit_of_measurement: A
 
  - platform: mqtt
    name: WiFiSwitch3_voltage
    state_topic: WiFiSwitch3/voltage
    unit_of_measurement: V
 
  - platform: mqtt
    name: WiFiSwitch3_power
    state_topic: WiFiSwitch3/power
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch3_reactive
    state_topic: WiFiSwitch3/reactive
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch3_apparent
    state_topic: WiFiSwitch3/apparent
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch3_factor
    state_topic: WiFiSwitch3/factor
    unit_of_measurement: '%'
 
  - platform: mqtt
    name: WiFiSwitch3_energy
    state_topic: WiFiSwitch3/energy
    unit_of_measurement: J

  - platform: mqtt
    name: WiFiSwitch4_current
    state_topic: WiFiSwitch4/current
    unit_of_measurement: A
 
  - platform: mqtt
    name: WiFiSwitch4_voltage
    state_topic: WiFiSwitch4/voltage
    unit_of_measurement: V
 
  - platform: mqtt
    name: WiFiSwitch4_power
    state_topic: WiFiSwitch4/power
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch4_reactive
    state_topic: WiFiSwitch4/reactive
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch4_apparent
    state_topic: WiFiSwitch4/apparent
    unit_of_measurement: W
 
  - platform: mqtt
    name: WiFiSwitch4_factor
    state_topic: WiFiSwitch4/factor
    unit_of_measurement: '%'
 
  - platform: mqtt
    name: WiFiSwitch4_energy
    state_topic: WiFiSwitch4/energy
    unit_of_measurement: J
     
  - platform: rest
    name: Carbon intensity
    resource_template: >-
      {% set regionid = 12 %}
      https://api.carbonintensity.org.uk/regional/regionid/{{ regionid }}
    value_template: "{{ value_json.data[0].data[0].intensity.index }}"
    json_attributes_path: "$.data[0].data[0]"
    json_attributes:
      - "intensity"
      - "generationmix"

  - platform: rest
    name: Gas consumption yesterday
    resource_template: >-
      {% set mprn = '2059966800' %}
      {% set serial = 'G4P01815061600' %}
      {% set date = as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') %}
      https://api.octopus.energy/v1/gas-meter-points/{{ mprn }}/meters/{{ serial }}/consumption/?period_from={{ date + 'T00:00:00' }}&period_to={{ date + 'T23:59:59' }}
    headers:
      Authorization: Basic c2tfbGl2ZV9BS0tlRGNQbTdrd0lia1d0a3IzakJYcHo=
    value_template: "{{ value_json.results|sum(attribute='consumption')|round(3) }}"
    unit_of_measurement: 'm³'
    json_attributes:
      - "results"

  - platform: template
    sensors:
      gas_cost_yesterday:
        friendly_name: Gas cost yesterday
        icon_template: mdi:cash-multiple
        value_template: >-
          {% set unit_price = 2.86 %}
          {% set standing_charge = 26.06 %}
          {% set calorific_value = 39.1 %}
          {% set usage = state_attr('sensor.gas_consumption_yesterday', 'results') %}
          {% if usage is defined and usage|count == 48 %}
            {{ ((states('sensor.gas_consumption_yesterday') | float * 1.02264 * calorific_value / 3.6) * unit_price / 100 + standing_charge / 100)|round(2) }}
          {% else %}
            Unknown
          {% endif %}
        unit_of_measurement: '£'

  - platform: rest
    name: Electricity consumption yesterday
    resource_template: >-
      {% set mpan = '1100006662930' %}
      {% set serial = '16P0145697' %}
      {% set date = as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') %}
      https://api.octopus.energy/v1/electricity-meter-points/{{ mpan }}/meters/{{ serial }}/consumption/?period_from={{ date + 'T00:00:00' }}&period_to={{ date + 'T23:59:59' }}
    headers:
      Authorization: Basic c2tfbGl2ZV9BS0tlRGNQbTdrd0lia1d0a3IzakJYcHo=
    value_template: "{{ value_json.results|sum(attribute='consumption')|round(3) }}"
    unit_of_measurement: 'kWh'
    json_attributes:
      - "results"

  - platform: template
    sensors:
      electricity_cost_yesterday:
        friendly_name: Electricity cost yesterday
        icon_template: mdi:cash-multiple
        value_template: >-
          {% set standing_charge = 25 %}
          {% set usage = state_attr('sensor.electricity_consumption_yesterday', 'results') %}
          {% if usage is defined and usage|count == 48 %}
            {% set ns = namespace(total=0) %}
            {% for p in range(0, 48) %}
              {% set time = as_timestamp(usage[p].interval_start)|timestamp_custom('%H:%M:%S') %}
              {% set unit_price = 15.96 %}
              {% if '00:30:00' <= time < '04:30:00' %}
                {% set unit_price = 5 %}
              {% endif %}
              {% set ns.total = ns.total + (usage[p].consumption * unit_price / 100) %}
            {% endfor %}
            {{ (ns.total + standing_charge / 100)|round(2) }}
          {% else %}
            Unknown
          {% endif %}
        unit_of_measurement: '£'

logger:
## turn off debug messages, generally...
  default: warn

  logs:
    homeassistant.components.evohome: debug
#   homeassistant.components.climate.evohome: debug
#   homeassistant.components.water_heater.evohome: debug
    evohomeclient2: debug
    evohomeasync: debug
    evohomeasync2: debug


