sensor.gas_cost:
  unit_of_measurement: GBP
  device_class: monetary
  state_class: total
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.gas_consumption:
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.electricity_cost:
  unit_of_measurement: GBP
  device_class: monetary
  state_class: total
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.electricity_consumption:
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.electricity_cost_off_peak:
  unit_of_measurement: GBP
  device_class: monetary
  state_class: total
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.electricity_consumption_off_peak:
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.total_energy_consumption:
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.total_energy_cost:
  unit_of_measurement: GBP
  device_class: monetary
  state_class: total
  last_reset: '1970-01-01T00:00:00+00:00'
